### ISSUE TITLE
Make availability to create reports use salsa_runner for non-selenium tests

### ISSUE THREAD

**Issue by gvozdeva-ira** [salsita/shishito#19]
For now if I try to use salsa runner with non-selenium tests - it's shows error dependent on driver settings. So it would be good to have runner works for non-selenium tests as well:
Errors on running:
File "E:\workspace\salsa-webqa\salsa_webqa\salsa_runner.py", line 40, in __init__
    self.driver_name = self.tc.gid('driver')
  File "E:\workspace\salsa-webqa\salsa_webqa\library\control_test.py", line 77, in gid
    if local_execution.lower() == 'true':
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by sankaritan** [comment]
To be resolved by https://github.com/salsita/shishito/pull/25
