### ISSUE TITLE
Error when running test project containing only none selenium tests

### ISSUE THREAD

**Issue by JHarman** [salsita/shishito#31]
When running test project containing only none selenium tests, test project ends with error during test initialization. 

Error message:
```
usage: voicekick_runner.py [options] [file_or_dir] [file_or_dir] [...]
voicekick_runner.py: error: unrecognized arguments: --html=....../integration_tests/results/2015-02-02_13-39-20/Firefox.html

Process finished with exit code 2
```

Steps to reproduce:
1. Create test project using latest shishito framework
2. Crete none selenium folder
3. Create none-selenium test
4. Run project (using default configuration)

Expected result: Tests are executed.
Actual result: Test ends in error during initialization

Note: Using --reporting simple parameter is workaround how to run none-selenium only test project.

**Comment by gvozdeva-ira** [comment]
Another workaround is:
1. didn't add config files from selenium tests to non-selenium
2. OR if project contain this files - "driver" value  should be empty in it

**Comment by sankaritan** [comment]
Obsolete with https://github.com/salsita/shishito/releases/tag/v2.0-beta
